language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

services:
  - postgresql
before_install:
  - sudo apt-get install -y unixodbc unixodbc-dev odbc-postgresql libsqliteodbc
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres