[package]
name = "odbc"
description = "ODBC FFI binding for Rust"
version = "0.2.0"
authors = ["Konstantin Salikhov <koka58@yandex.ru>"]
repository = "https://github.com/Koka/odbc-rs"
documentation = "http://koka.github.io/odbc-rs/odbc/"
homepage = "https://github.com/Koka/odbc-rs"
readme = "README.md"
keywords = ["odbc", "binding", "ffi", "database", "db"]
license = "MIT"

[dependencies]
