[package]
name = "odbc"
description = "ODBC wrapper for idiomatic Rust"
version = "0.5.0"
authors = ["Konstantin Salikhov <koka58@yandex.ru>"]
repository = "https://github.com/Koka/odbc-rs"
documentation = "http://koka.github.io/odbc-rs/odbc/"
homepage = "https://github.com/Koka/odbc-rs"
readme = "README.md"
keywords = ["odbc", "binding", "sql", "database", "db"]
license = "MIT"
categories = ["api-bindings", "database"]

[dependencies]
odbc-sys = "0.2.7"
log = "0.3.7"

[dev-dependencies]
env_logger = "0.3"
